# These are supported funding model platforms

github: [] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: ['https://www.patreon.com/kouyou'] # Replace with a single Patreon username
custom: ['https://afdian.net/@Kouyou'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
